# Guarneri-style device YAML configuration

# Objects only available at APS

id8_common.devices.patched_aps.PatchedApsMachineParametersDevice:
  - name: aps


# apstools.devices.ApsMachineParametersDevice:
# - name: aps
#   labels:
#   - baseline
